### ISSUE TITLE
Add overlap between screens

### ISSUE THREAD

**Issue by felipefialho** [morajabi/styled-media-query#25]
Hi, first I would like to thank you for this project 😊

My issue is about overlap between screens, for now we have some problems about it, for example:

```css
${media.lessThan("medium")`
  /* screen width is less than 768px (medium) */
  background: red;
`}

${media.greaterThan("medium")`
   /* screen width is greater than 768px (medium) */
  background: blue;
`}
```

The both examples will be happens if screen is exactly `768px`.

Maybe a good ideia is use an approach like the [Rupture](https://github.com/CubaSAN/rupture-sass).

Thanks!
